title: Matthias Kiefer Gross
remote_theme: S3lected/texture
repository: S3lected/S3lected.github.io

texture:
    title: Matthias Kiefer
    tagline: Developer. Architect.
    date_format: "%d.%M.%Y"
    style: black
    showNav: true

    social_links:
        github: S3lected
        linkedIn: in/matthias-konrad-kiefer/